# Site settings
title: Phil Schneider
email: philipschneider4@gmail.com
description: The Jekyll version of the Identity theme by HTML5 UP.
baseurl: "/stuff" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Philip Schneider
your-title: Engineer

# Social settings
500px_url:
facebook_url: 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
