# Site settings
title: Identity
email: philipschneider4@gmail.com
description: The Jekyll version of the Identity theme by HTML5 UP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "philaschneider.com" # the base hostname & protocol for your site

# Identity
your-name: Phil Schneider
your-title: Engineer

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/Schnep45
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/philip-schneider-b582411aa/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
